### ISSUE TITLE
Converting Altium files to gerber files?

### ISSUE THREAD

**Issue by JustGitting** [mhycy/hardware-gen8-pwm-convert#1]
嗨，我的天

很高兴看到这个项目。

我想为我的Gen8制作你的电路板，但我没有Altium EDA软件。

你是否可以将Alitum的专有文件导出为开放标准，如Gerber？

另外，你有你使用的零件的材料清单（BOM）吗？具体来说，你从哪里得到6针直角插头？

谢谢您

-------------------------------
 
Hi,

Great to see this project.

I'd like to make your board for my Gen8, but I don't have the Altium EDA software.

Are you able to export the Alitum proprietary files to an open standard such as Gerber?

Also, do you have a bill of materials (BOM) for the parts you used? Specifically, where did you get the 6-pin right angle plugs?

Thank you.

**Comment by mhycy** [comment]
6针直角插头购买自淘宝/嘉立创（所有元件都来自于这两个地方）
至于转换，我本职工作是Web全栈开发，所以现在并没有装这软件
所以只能自给自足啦，也不打算更新这个项目了
BOM清单没有导出，但原理图上都有标记，照着买就好

**Comment by JustGitting** [comment]
好的，谢谢你
